# Generated by Django 5.2.8 on 2025-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_followers_count_user_following_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='styleprofile',
            options={'verbose_name': 'Style Profile', 'verbose_name_plural': 'Style Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('outfit_ready', 'Outfit Ready'), ('weather_alert', 'Weather Alert'), ('social_like', 'Social Like'), ('social_comment', 'Social Comment'), ('challenge', 'Style Challenge'), ('recommendation', 'Recommendation'), ('system', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='styleprofile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('triangle', 'Triangle'), ('triangle_inverse', 'Inverted Triangle'), ('sablier', 'Hourglass'), ('ovale', 'Oval')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Standard User'), ('premium', 'Premium User'), ('stylist', 'Stylist'), ('influencer', 'Influencer'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=20),
        ),
    ]
