# Generated by Django 5.2.8 on 2025-12-09 11:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_initial'),
        ('users', '0004_user_password_change_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleprofile',
            name='coach_mode',
            field=models.CharField(choices=[('gentle', 'Gentle Guide'), ('strict', 'Strict Stylist'), ('educational', 'Professor of Style')], default='gentle', max_length=20),
        ),
        migrations.AddField(
            model_name='styleprofile',
            name='learning_focus',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='FashionIQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_level', models.CharField(choices=[('novice', 'Fashion Novice'), ('intermediate', 'Style Enthusiast'), ('advanced', 'Taste Maker'), ('expert', 'Style Icon')], default='novice', max_length=20)),
                ('total_xp', models.IntegerField(default=0)),
                ('color_score', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pattern_score', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('silhouette_score', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('versatility_score', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lessons_completed', models.IntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('areas_for_improvement', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_iq', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fashion IQ',
                'verbose_name_plural': 'Fashion IQs',
                'db_table': 'fashion_iq',
            },
        ),
        migrations.CreateModel(
            name='StyleCritiqueSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outfit_image', models.ImageField(blank=True, null=True, upload_to='critiques/')),
                ('critique_text', models.TextField()),
                ('suggestion_text', models.TextField()),
                ('concept_taught', models.CharField(blank=True, max_length=100)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critiques', to='outfits.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critique_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Style Critique',
                'verbose_name_plural': 'Style Critiques',
                'db_table': 'style_critiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
