# Generated by Django 5.2.8 on 2025-12-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_styleprofile_coach_mode_styleprofile_learning_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecritiquesession',
            name='xp_gained',
            field=models.IntegerField(default=0),
        ),
    ]
