# Generated by Django 5.2.8 on 2025-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_stylecritiquesession_xp_gained'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashioniq',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fashioniq',
            name='last_good_outfit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fashioniq',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
