# Generated by Django 5.2.8 on 2025-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fashioniq_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
