# Generated by Django 5.2.8 on 2025-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleprofile',
            name='ai_palette',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
