# Generated by Django 5.2.7 on 2025-11-04 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='wardrobe.clothingcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie de Vêtement',
                'verbose_name_plural': 'Catégories de Vêtements',
                'db_table': 'clothing_categories',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='wardrobe/')),
                ('color', models.CharField(max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('pattern', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('seasons', models.JSONField(default=list)),
                ('occasions', models.JSONField(default=list)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_location', models.CharField(blank=True, max_length=200)),
                ('is_secondhand', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('washing', 'Au Lavage'), ('dry_cleaning', 'Au Pressing'), ('loaned', 'Prêté'), ('repair', 'En Réparation')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('excellent', 'Excellent'), ('good', 'Bon'), ('fair', 'Correct'), ('worn', 'Usé')], default='good', max_length=20)),
                ('times_worn', models.IntegerField(default=0)),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='wardrobe.clothingcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vêtement',
                'verbose_name_plural': 'Vêtements',
                'db_table': 'clothing_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='clothing_it_user_id_c3b344_idx'), models.Index(fields=['user', 'status'], name='clothing_it_user_id_e0b7b6_idx'), models.Index(fields=['user', 'favorite'], name='clothing_it_user_id_a162bb_idx')],
            },
        ),
    ]
