# Generated by Django 5.2.8 on 2025-12-09 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_weeklyplan_dailyplanslot_and_more'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='care_type',
            field=models.CharField(choices=[('machine_wash', 'Machine Washable'), ('hand_wash', 'Hand Wash'), ('dry_clean', 'Dry Clean Only'), ('spot_clean', 'Spot Clean')], default='machine_wash', max_length=20),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='drying_time_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='last_washed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='max_wears_before_wash',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='wears_since_wash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('washing', 'Au Lavage'), ('dry_cleaning', 'Au Pressing'), ('loaned', 'Prêté'), ('repair', 'En Réparation'), ('drying', 'En Séchage')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='LaundryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_date', models.DateField()),
                ('alert_type', models.CharField(choices=[('needs_washing', 'Needs Washing'), ('drying_time', 'Needs Time to Dry'), ('at_cleaners', 'Still at Dry Cleaners'), ('approaching', 'Approaching Wash Limit')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_alerts', to='wardrobe.clothingitem')),
                ('daily_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laundry_alerts', to='planner.dailyplanslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laundry Alert',
                'verbose_name_plural': 'Laundry Alerts',
                'db_table': 'laundry_alerts',
                'ordering': ['deadline', '-priority'],
                'indexes': [models.Index(fields=['user', 'is_resolved'], name='laundry_ale_user_id_ea8d59_idx'), models.Index(fields=['user', 'planned_date'], name='laundry_ale_user_id_fcbb1b_idx')],
            },
        ),
    ]
