# Generated by Django 5.2.7 on 2025-11-04 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'post_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "J'aime",
                'verbose_name_plural': "J'aimes",
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='PostSave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication Sauvegardée',
                'verbose_name_plural': 'Publications Sauvegardées',
                'db_table': 'post_saves',
            },
        ),
        migrations.CreateModel(
            name='StyleChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'À Venir'), ('active', 'En Cours'), ('completed', 'Terminé')], default='upcoming', max_length=20)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('hashtag', models.CharField(max_length=50, unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='challenges/')),
                ('participants_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Défi de Style',
                'verbose_name_plural': 'Défis de Style',
                'db_table': 'style_challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'user_follows',
            },
        ),
        migrations.CreateModel(
            name='LookbookPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnés Seulement'), ('private', 'Privé')], default='public', max_length=20)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbook_posts', to='outfits.outfit')),
            ],
            options={
                'verbose_name': 'Publication Lookbook',
                'verbose_name_plural': 'Publications Lookbook',
                'db_table': 'lookbook_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
