# Generated by Django 5.2.8 on 2025-11-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbookpost',
            name='enhanced_images',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
