# Generated by Django 5.2.8 on 2025-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbookpost',
            name='current_badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
