# Generated by Django 5.2.8 on 2025-12-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_add_drafts_badges_ai_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbookpost',
            name='enhancement_style',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
