# Generated by Django 5.2.8 on 2025-12-09 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_initial'),
        ('social', '0005_lookbookpost_current_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookbookpost',
            name='current_badge',
        ),
        migrations.CreateModel(
            name='PostDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('enhanced_images', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnés Seulement'), ('private', 'Privé')], default='public', max_length=20)),
                ('ai_optimized_hashtags', models.JSONField(blank=True, default=list)),
                ('ai_suggested_captions', models.JSONField(blank=True, default=list)),
                ('ai_best_time', models.DateTimeField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(default=0.0)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('published', 'Publié')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_drafts', to='outfits.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brouillon de Publication',
                'verbose_name_plural': 'Brouillons de Publication',
                'db_table': 'post_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEngagementData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('optimal_post_time', models.DateTimeField()),
                ('hashtag_suggestions', models.JSONField(default=list)),
                ('caption_suggestions', models.JSONField(default=list)),
                ('predicted_likes', models.IntegerField(default=0)),
                ('predicted_comments', models.IntegerField(default=0)),
                ('predicted_saves', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('user_best_time_window', models.CharField(blank=True, max_length=50)),
                ('best_performing_hashtags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='social.lookbookpost')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='social.postdraft')),
            ],
            options={
                'verbose_name': "Données d'Engagement IA",
                'verbose_name_plural': "Données d'Engagement IA",
                'db_table': 'ai_engagement_data',
            },
        ),
    ]
