# Generated by Django 5.2.7 on 2025-11-04 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('occasion', models.CharField(choices=[('casual', 'Décontracté'), ('work', 'Bureau'), ('formal', 'Formel'), ('sport', 'Sport'), ('evening', 'Soirée'), ('weekend', 'Week-end'), ('wedding', 'Mariage'), ('travel', 'Voyage'), ('date', 'Rendez-vous'), ('other', 'Autre')], default='casual', max_length=20)),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('user', 'Créé par Utilisateur'), ('ai', 'Suggestion IA'), ('community', 'Inspiré Communauté')], default='user', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('times_worn', models.IntegerField(default=0)),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('min_temperature', models.IntegerField(blank=True, null=True)),
                ('max_temperature', models.IntegerField(blank=True, null=True)),
                ('suitable_weather', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit_image', models.ImageField(blank=True, null=True, upload_to='outfits/')),
            ],
            options={
                'verbose_name': 'Tenue',
                'verbose_name_plural': 'Tenues',
                'db_table': 'outfits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer', models.CharField(choices=[('base', 'Base Layer'), ('mid', 'Mid Layer'), ('outer', 'Outer Layer'), ('accessory', 'Accessory'), ('shoes', 'Shoes')], default='base', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('x_position', models.FloatField(blank=True, null=True)),
                ('y_position', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outfit_items',
                'ordering': ['position'],
            },
        ),
    ]
