# Generated by Django 5.2.7 on 2025-11-04 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0001_initial'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfititem',
            name='clothing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_memberships', to='wardrobe.clothingitem'),
        ),
        migrations.AddField(
            model_name='outfititem',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_items', to='outfits.outfit'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(related_name='outfits', through='outfits.OutfitItem', to='wardrobe.clothingitem'),
        ),
        migrations.AlterUniqueTogether(
            name='outfititem',
            unique_together={('outfit', 'clothing_item')},
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['user', 'occasion'], name='outfits_user_id_9e5433_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['user', 'favorite'], name='outfits_user_id_73f155_idx'),
        ),
    ]
