# Generated by Django 5.2.6 on 2025-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_stylechallenge_challengeparticipation_userbadge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylechallenge',
            name='challenge_type',
            field=models.CharField(choices=[('capsule', 'Capsule Wardrobe'), ('color', 'Color Theme'), ('item', 'Specific Item'), ('style', 'Style Exploration'), ('sustainability', 'Sustainability'), ('daily', 'Daily Style'), ('weekly', 'Weekly Theme')], default='capsule', max_length=20),
        ),
        migrations.AlterField(
            model_name='stylechallenge',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
