# Generated by Django 5.2.7 on 2025-11-04 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trip_type', models.CharField(blank=True, max_length=50)),
                ('expected_weather', models.JSONField(blank=True, default=dict)),
                ('planned_activities', models.JSONField(blank=True, default=list)),
                ('packing_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Voyage',
                'verbose_name_plural': 'Plans de Voyage',
                'db_table': 'travel_plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WearHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worn_date', models.DateField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comfort_rating', models.IntegerField(blank=True, null=True)),
                ('received_compliments', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de Port',
                'verbose_name_plural': 'Historiques de Port',
                'db_table': 'wear_history',
                'ordering': ['-worn_date'],
            },
        ),
        migrations.CreateModel(
            name='OutfitPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('event_description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('weather_alert', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('was_worn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='outfits.outfit')),
            ],
            options={
                'verbose_name': 'Planification de Tenue',
                'verbose_name_plural': 'Planifications de Tenues',
                'db_table': 'outfit_plannings',
                'ordering': ['date'],
            },
        ),
    ]
