# Generated by Django 5.2.7 on 2025-11-04 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0002_initial'),
        ('planner', '0001_initial'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitplanning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_plannings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='additional_items',
            field=models.ManyToManyField(blank=True, related_name='travel_plans', to='wardrobe.clothingitem'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='outfits',
            field=models.ManyToManyField(blank=True, related_name='travel_plans', to='outfits.outfit'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wearhistory',
            name='clothing_items',
            field=models.ManyToManyField(related_name='wear_history', to='wardrobe.clothingitem'),
        ),
        migrations.AddField(
            model_name='wearhistory',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wear_history', to='outfits.outfit'),
        ),
        migrations.AddField(
            model_name='wearhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='outfitplanning',
            index=models.Index(fields=['user', 'date'], name='outfit_plan_user_id_7d7e6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outfitplanning',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='wearhistory',
            index=models.Index(fields=['user', 'worn_date'], name='wear_histor_user_id_3773af_idx'),
        ),
    ]
