# Generated by Django 5.2.7 on 2025-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
