# Generated by Django 5.2.8 on 2025-12-09 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_initial'),
        ('planner', '0003_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('weather_data', models.JSONField(blank=True, default=dict)),
                ('events_considered', models.JSONField(blank=True, default=list)),
                ('generation_reasoning', models.TextField(blank=True)),
                ('location', models.CharField(default='Tunis', max_length=100)),
                ('overall_rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Plan',
                'verbose_name_plural': 'Weekly Plans',
                'db_table': 'weekly_plans',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlanSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_of_week', models.IntegerField()),
                ('suggested_items', models.JSONField(blank=True, default=list)),
                ('suggested_name', models.CharField(blank=True, max_length=200)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=20)),
                ('selection_reason', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('weather_score', models.FloatField(default=0.0)),
                ('occasion_score', models.FloatField(default=0.0)),
                ('recency_score', models.FloatField(default=0.0)),
                ('style_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('suggested', 'AI Suggested'), ('accepted', 'User Accepted'), ('modified', 'User Modified'), ('skipped', 'Skipped'), ('worn', 'Worn')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternatives', models.ManyToManyField(blank=True, related_name='alternative_daily_slots', to='outfits.outfit')),
                ('events', models.ManyToManyField(blank=True, related_name='daily_plan_slots', to='planner.event')),
                ('primary_outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_daily_slots', to='outfits.outfit')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='planner.weeklyplan')),
            ],
            options={
                'verbose_name': 'Daily Plan Slot',
                'verbose_name_plural': 'Daily Plan Slots',
                'db_table': 'daily_plan_slots',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['user', 'week_start'], name='weekly_plan_user_id_768528_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['user', 'status'], name='weekly_plan_user_id_0cfb89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together={('user', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='dailyplanslot',
            index=models.Index(fields=['weekly_plan', 'date'], name='daily_plan__weekly__543631_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplanslot',
            index=models.Index(fields=['status'], name='daily_plan__status_73b2bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplanslot',
            unique_together={('weekly_plan', 'date')},
        ),
    ]
