# Generated by Django 5.2.7 on 2025-11-04 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('color', 'Couleur'), ('pattern', 'Motif'), ('season', 'Saison'), ('occasion', 'Occasion'), ('proportion', 'Proportion'), ('style_mix', 'Mélange de Styles')], max_length=50)),
                ('rule_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('conditions', models.JSONField(default=dict)),
                ('recommendation', models.TextField()),
                ('importance', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Règle de Style',
                'verbose_name_plural': 'Règles de Style',
                'db_table': 'style_rules',
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('outfit_created', 'Tenue Créée'), ('outfit_liked', 'Tenue Aimée'), ('outfit_worn', 'Tenue Portée'), ('outfit_rated', 'Tenue Notée'), ('item_favorited', 'Article Favori'), ('recommendation_accepted', 'Recommandation Acceptée'), ('recommendation_rejected', 'Recommandation Rejetée'), ('post_liked', 'Publication Aimée'), ('style_updated', 'Style Mis à Jour')], max_length=50)),
                ('signal_value', models.FloatField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signal de Préférence',
                'verbose_name_plural': 'Signaux de Préférence',
                'db_table': 'user_preference_signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColorCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color1', models.CharField(max_length=50)),
                ('color1_hex', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=50)),
                ('color2_hex', models.CharField(max_length=7)),
                ('compatibility_score', models.FloatField()),
                ('relationship_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Compatibilité des Couleurs',
                'verbose_name_plural': 'Compatibilités des Couleurs',
                'db_table': 'color_compatibility',
                'unique_together': {('color1', 'color2')},
            },
        ),
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_date', models.DateField()),
                ('priority', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('weather_factor', models.JSONField(blank=True, default=dict)),
                ('style_match_score', models.FloatField(default=0.0)),
                ('occasion_match', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En Attente'), ('viewed', 'Vue'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('worn', 'Portée')], default='pending', max_length=20)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='outfits.outfit')),
            ],
            options={
                'verbose_name': 'Recommandation Quotidienne',
                'verbose_name_plural': 'Recommandations Quotidiennes',
                'db_table': 'daily_recommendations',
                'ordering': ['recommendation_date', 'priority'],
            },
        ),
    ]
