# Generated by Django 5.2.7 on 2025-11-04 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0002_initial'),
        ('recommendations', '0001_initial'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferencesignal',
            name='clothing_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_signals', to='wardrobe.clothingitem'),
        ),
        migrations.AddField(
            model_name='userpreferencesignal',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_signals', to='outfits.outfit'),
        ),
        migrations.AddField(
            model_name='userpreferencesignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendation',
            index=models.Index(fields=['user', 'recommendation_date'], name='daily_recom_user_id_37cef5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendation',
            index=models.Index(fields=['user', 'status'], name='daily_recom_user_id_8f1b99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecommendation',
            unique_together={('user', 'recommendation_date', 'outfit')},
        ),
        migrations.AddIndex(
            model_name='userpreferencesignal',
            index=models.Index(fields=['user', 'signal_type'], name='user_prefer_user_id_6a986a_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencesignal',
            index=models.Index(fields=['user', '-created_at'], name='user_prefer_user_id_3ea2bb_idx'),
        ),
    ]
