# Generated by Django 5.2.7 on 2025-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorcompatibility',
            options={'verbose_name': 'Color Compatibility', 'verbose_name_plural': 'Color Compatibilities'},
        ),
        migrations.AlterModelOptions(
            name='dailyrecommendation',
            options={'ordering': ['recommendation_date', 'priority'], 'verbose_name': 'Daily Recommendation', 'verbose_name_plural': 'Daily Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='stylerule',
            options={'verbose_name': 'Style Rule', 'verbose_name_plural': 'Style Rules'},
        ),
        migrations.AlterModelOptions(
            name='userpreferencesignal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Preference Signal', 'verbose_name_plural': 'Preference Signals'},
        ),
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('worn', 'Worn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stylerule',
            name='category',
            field=models.CharField(choices=[('color', 'Color'), ('pattern', 'Pattern'), ('season', 'Season'), ('occasion', 'Occasion'), ('proportion', 'Proportion'), ('style_mix', 'Style Mix')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreferencesignal',
            name='signal_type',
            field=models.CharField(choices=[('outfit_created', 'Outfit Created'), ('outfit_liked', 'Outfit Liked'), ('outfit_worn', 'Outfit Worn'), ('outfit_rated', 'Outfit Rated'), ('item_favorited', 'Item Favorited'), ('recommendation_accepted', 'Recommendation Accepted'), ('recommendation_rejected', 'Recommendation Rejected'), ('post_liked', 'Post Liked'), ('style_updated', 'Style Updated')], max_length=50),
        ),
    ]
