# Generated by Django 5.2.8 on 2025-11-26 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_colorcompatibility_options_and_more'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('suggested_name', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Low - Nice to have'), (2, 'Medium - Recommended'), (3, 'High - Wardrobe essential'), (4, 'Critical - Missing basic'), (5, 'Urgent - Complete existing outfit')], default=2)),
                ('versatility_score', models.FloatField(default=0.0)),
                ('estimated_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shopping_keywords', models.JSONField(blank=True, default=list)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complements', models.ManyToManyField(blank=True, related_name='complement_suggestions', to='wardrobe.clothingitem')),
                ('purchased_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_source', to='wardrobe.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping Recommendation',
                'verbose_name_plural': 'Shopping Recommendations',
                'db_table': 'shopping_recommendations',
                'ordering': ['-priority', '-versatility_score'],
                'indexes': [models.Index(fields=['user', 'is_purchased', 'is_dismissed'], name='shopping_re_user_id_3bc971_idx'), models.Index(fields=['user', '-priority'], name='shopping_re_user_id_b5cb0b_idx')],
            },
        ),
    ]
