# Generated by Django 5.2.8 on 2025-12-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_initial'),
        ('recommendations', '0004_shoppingrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='outfits.outfit'),
        ),
    ]
