# Generated by Django 5.2.8 on 2025-12-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_dailyrecommendation_outfit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyrecommendation',
            unique_together=set(),
        ),
    ]
